import fetch from 'node-fetch';
import fs from 'fs/promises';
import path from 'path';

let handler = m => m;

handler.all = async function (m) {
  for (const message in audioMsg) {
    if (new RegExp(`^${message}$`, 'i').test(m.text)) {
      let file = audioMsg[message];
      
      try {
        if (file.startsWith('http')) {
          // Descargar archivo de la URL
          const response = await fetch(file);
          if (!response.ok) throw new Error(`Failed to fetch ${file}`);
          const buffer = await response.buffer();
          await this.sendFile(m.chat, buffer, 'audio.mp3', null, m, true);
        } else {
          // Convertir la ruta relativa a una ruta absoluta
          const absolutePath = path.resolve(file);
          // Verificar si el archivo local existe usando fs.promises.access
          await fs.access(absolutePath); // Si el archivo no existe, lanzará un error
          await this.sendFile(m.chat, absolutePath, 'audio.mp3', null, m, true);
        }
      } catch (error) {
        console.error(`Error handling file for message "${message}": ${error.message}`);
        // Log adicional para depuración
        if (error.code === 'ENOENT') {
          console.error(`File not found: ${error.path}`);
        }
      }
      
      break;
    }
  }
  return !0;
}

export default handler;

let audioMsg = {
  'fino': './src/mp3/fino.mp3',
  'buenos días': 'https://k.top4top.io/m_2826iqdri1.mp3',
  'buenas tardes': 'https://b.top4top.io/m_2826v2zg51.mp3',
  'buenas noches': 'https://i.top4top.io/m_2826o8rfj1.mp3',
  'sad': 'https://h.top4top.io/m_2826mcim21.mp3',
  'pela': './src/mp3/melapela.mp3',
  'awebo': './src/mp3/awebo.m4a',
  'chupa chupa hijo la gran puta': './src/mp3/WhatsApp.mhtml',
  'hasta que me explote el huevo': './src/mp3/WhatsApp.mhtml',
  'callate la boca': './src/mp3/callate la boca.opus',
  'no estoy hablando': './src/mp3/callate la boca.opus',
  'bañate': './src/mp3/Banate.mp3',
  'silencio': './src/mp3/callate la boca.opus',
  'chupa': './src/mp3/chupa.m4a',
  'vives': './src/mp3/elmo_sabe_donde_vives.m4a',
  'sabe': './src/mp3/elmo_sabe_donde_vives.m4a',
  'esnifar': './src/mp3/snifar_coca.m4a',
  'coca': './src/mp3/snifar_coca.m4a',
  'droga': './src/mp3/snifar_coca.m4a',
  'marihuana': './src/mp3/snifar_coca.m4a',
  'snifar': './src/mp3/snifar_coca.m4a',
  'drogarse': './src/mp3/snifar_coca.m4a',
  'cariñosas': './src/mp3/cariñosas.mp3',
  'chingon': './src/mp3/elmo_es_chingon.mp3',
  'elmo': './src/mp3/elmo_es_chingon.mp3',
  'dijiste': './src/mp3/que_dijistes.mp3',
  'te crees mejor': './src/mp3/te_crees_mejor_q_elmo.mp3',
  'chulo': './src/mp3/te_crees_mejor_q_elmo.mp3',
  'te revelas': './src/mp3/te_revelas.mp3',
  'adios': './src/mp3/A bueno adios master.mp3',
  'A Bueno master': './src/mp3/A bueno adios master.mp3',
  'Bueno master': './src/mp3/A bueno adios master.mp3',
  'Bueno Máster': './src/mp3/A bueno adios master.mp3',
  '🫂': './src/mp3/A bueno adios master.mp3',
  'bienveni': './src/mp3/Bienvenido.mp3',
  '🥳': './src/mp3/Bienvenido.mp3',
  '🤗': './src/mp3/Bienvenido.mp3',
  '👋': './src/mp3/Bienvenido.mp3',
  'Blackpink in your area': './src/mp3/Blackpink in your area.mp3',
  'blackpink in your area': './src/mp3/Blackpink in your area.mp3',
  'in your area': './src/mp3/Blackpink in your area.mp3',
  'In your area': './src/mp3/Blackpink in your area.mp3',
  'Buen día grupo': './src/mp3/Buen día grupo.mp3',
  'Buen dia grupo': './src/mp3/Buen día grupo.mp3',
  '🙌': './src/mp3/Buen día grupo.mp3',
  'Calla Fan de bts': './src/mp3/Calla Fan de BTS.mp3',
  'bts': './src/mp3/Calla Fan de BTS.mp3',
  'Amo a bts': './src/mp3/Calla Fan de BTS.mp3',
  'Cambiate a Movistar': './src/mp3/Cambiate a Movistar.mp3',
  'cambiate a Movistar': './src/mp3/Cambiate a Movistar.mp3',
  'cambiate a movistar': './src/mp3/Cambiate a Movistar.mp3',
  'Cambiate a movistar': './src/mp3/Cambiate a Movistar.mp3',
  'movistar': './src/mp3/Cambiate a Movistar.mp3',
  'Corte Corte': './src/mp3/Corte Corte.mp3',
  'corte': './src/mp3/Corte Corte.mp3',
  'pelea': './src/mp3/Corte Corte.mp3',
  'pelear': './src/mp3/Corte Corte.mp3',
  'golpear': './src/mp3/Corte Corte.mp3',
  'golpea': './src/mp3/Corte Corte.mp3',
  'El Toxico': './src/mp3/El Toxico.mp3',
  'El tóxico': './src/mp3/El Toxico.mp3',
  'Toxico': './src/mp3/El Toxico.mp3',
  'tóxico': './src/mp3/El Toxico.mp3',
  'malo': './src/mp3/El Toxico.mp3',
  'mala': './src/mp3/El Toxico.mp3',
  'estupido': './src/mp3/El Toxico.mp3',
  'estupida': './src/mp3/El Toxico.mp3',
  'Elmo sabe donde vives': './src/mp3/Elmo sabe donde vives.mp3',
  'Elmo sabe dónde vives': './src/mp3/Elmo sabe donde vives.mp3',
  'elmo': './src/mp3/Elmo sabe donde vives.mp3',
  'vives': './src/mp3/Elmo sabe donde vives.mp3',
  'de donde eres': './src/mp3/Elmo sabe donde vives.mp3',
  'eres de': './src/mp3/Elmo sabe donde vives.mp3',
  'sabes': './src/mp3/Elmo sabe donde vives.mp3',
  'En caso de una investigación': './src/mp3/En caso de una investigación.mp3',
  'En caso de una investigacion': './src/mp3/En caso de una investigación.mp3',
  'investigacion': './src/mp3/En caso de una investigación.mp3',
  'fbi': './src/mp3/En caso de una investigación.mp3',
  'cia': './src/mp3/En caso de una investigación.mp3',
  'nasa': './src/mp3/En caso de una investigación.mp3',
  'detective': './src/mp3/En caso de una investigación.mp3',
  '👤': './src/mp3/En caso de una investigación.mp3',
  '🕵️‍': './src/mp3/En caso de una investigación.mp3',
  '♀️🕵️‍♂️': './src/mp3/En caso de una investigación.mp3',
  'Eres Fuerte': './src/mp3/Eres Fuerte.mp3',
  'god': './src/mp3/Eres Fuerte.mp3',
  '🙌': './src/mp3/Eres Fuerte.mp3',
  '🤜': './src/mp3/Eres Fuerte.mp3',
  '🤛': './src/mp3/Eres Fuerte.mp3',
  '🦾': './src/mp3/Eres Fuerte.mp3',
  '💪': './src/mp3/Eres Fuerte.mp3',
  '👊': './src/mp3/Eres Fuerte.mp3',
  'Zzzz': './src/mp3/Esta Zzzz.mp3',
  'zzz': './src/mp3/Esta Zzzz.mp3',
  '😴': './src/mp3/Esta Zzzz.mp3',
  '💩': './src/mp3/Esta Zzzz.mp3',
  '👾': './src/mp3/Esta Zzzz.mp3',
  '👽': './src/mp3/Esta Zzzz.mp3',
  '🎃': './src/mp3/Esta Zzzz.mp3',
  'Las reglas del grupo': './src/mp3/Las reglas del grupo.mp3',
  'lee': './src/mp3/Las reglas del grupo.mp3',
  'leíste': './src/mp3/Las reglas del grupo.mp3',
  'leiste': './src/mp3/Las reglas del grupo.mp3',
  'Me anda buscando anonymous': './src/mp3/Me anda buscando anonymous.mp3',
  'me anda buscando anonymous': './src/mp3/Me anda buscando anonymous.mp3',
  'Me está buscando anonymous': './src/mp3/Me anda buscando anonymous.mp3',
  'me está buscando anonymous': './src/mp3/Me anda buscando anonymous.mp3',
  'Me está buscando anonimo': './src/mp3/Me anda buscando anonymous.mp3',
  'Me esta buscando anonimo': './src/mp3/Me anda buscando anonymous.mp3',
  'anonimus': './src/mp3/Me anda buscando anonymous.mp3',
  'anónimo': './src/mp3/Me anda buscando anonymous.mp3',
  'buscan': './src/mp3/Me anda buscando anonymous.mp3',
  'Momento equisde': './src/mp3/Momento equisde.mp3',
  'momento equisde': './src/mp3/Momento equisde.mp3',
  'Momento': './src/mp3/Momento equisde.mp3',
  'fuera': './src/mp3/Momento equisde.mp3',
  '🥴': './src/mp3/Momento equisde.mp3',
  '😨': './src/mp3/Momento equisde.mp3',
  '🤘': './src/mp3/Momento equisde.mp3',
  '👄': './src/mp3/Momento equisde.mp3',
  '🕴️': './src/mp3/Momento equisde.mp3',
  '💃': './src/mp3/Momento equisde.mp3',
  '🕺': './src/mp3/Momento equisde.mp3',
  'Motivacion': './src/mp3/Motivacion.mp3',
  'Motivación': './src/mp3/Motivacion.mp3',
  '💫': './src/mp3/Motivacion.mp3',
  '✨': './src/mp3/Motivacion.mp3',
  '💥': './src/mp3/Motivacion.mp3',
  '☘️': './src/mp3/Motivacion.mp3',
  '⭐': './src/mp3/Motivacion.mp3',
  'Muchachos': './src/mp3/Muchachos.mp3',
  '⛈️': './src/mp3/Muchachos.mp3',
  '🌩️': './src/mp3/Muchachos.mp3',
  '🌦️': './src/mp3/Muchachos.mp3',
  '🌤️': './src/mp3/Muchachos.mp3',
  '🌪️': './src/mp3/Muchachos.mp3',
  'escucharon': './src/mp3/Muchachos.mp3',
  'Nico Nico': './src/mp3/Nico Nico.mp3',
  '🐄': './src/mp3/Nico Nico.mp3',
  '🐖': './src/mp3/Nico Nico.mp3',
  '🐬': './src/mp3/Nico Nico.mp3',
  '🐼': './src/mp3/Nico Nico.mp3',
  '🐰': './src/mp3/Nico Nico.mp3',
  '🐆': './src/mp3/Nico Nico.mp3',
  '🐇': './src/mp3/Nico Nico.mp3',
  '🦦': './src/mp3/Nico Nico.mp3',
  '🐋': './src/mp3/Nico Nico.mp3',
  'No Rompas más': './src/mp3/No Rompas Mas.mp3',
  'No Rompas mas': './src/mp3/No Rompas Mas.mp3',
  '💔': './src/mp3/No Rompas Mas.mp3',
  '😖': './src/mp3/No Rompas Mas.mp3',
  '😫': './src/mp3/No Rompas Mas.mp3',
  '😣': './src/mp3/No Rompas Mas.mp3',
  '😿': './src/mp3/No Rompas Mas.mp3',
  'Porque ta tite': './src/mp3/Porque ta tite.mp3',
  'Por qué ta tite': './src/mp3/Porque ta tite.mp3',
  '🥺': './src/mp3/Porque ta tite.mp3',
  '😕': './src/mp3/Porque ta tite.mp3',
  '😟': './src/mp3/Porque ta tite.mp3',
  '😞': './src/mp3/Porque ta tite.mp3',
  '😔': './src/mp3/Porque ta tite.mp3',
  'Potaxio': './src/mp3/Potaxio.mp3',
  'Potasio': './src/mp3/Potaxio.mp3',
  '🥑': './src/mp3/Potaxio.mp3',
  'Que tal Grupo': './src/mp3/Que tal Grupo.mp3',
  'qué tal grupo': './src/mp3/Que tal Grupo.mp3',
  'grupos': './src/mp3/Que tal Grupo.mp3',
  // Definir las rutas de los archivos de audio en un objeto para simplificar la gestión
  'Se están riendo de mí': './src/mp3/Se estan riendo de mi.mp3',
  'Se estan riendo de mi': './src/mp3/Se estan riendo de mi.mp3',
  'Se esta riendo de mi': './src/mp3/Se estan riendo de mi.mp3',
  'Se está riendo de mi': './src/mp3/Se estan riendo de mi.mp3',
  'se estan': './src/mp3/Se estan riendo de mi.mp3',

  'Su nivel de pendejo': './src/mp3/Su nivel de pendejo.mp3',
  'pendeja': './src/mp3/Su nivel de pendejo.mp3',
  'pendejo': './src/mp3/Su nivel de pendejo.mp3',
  'idiota': './src/mp3/Su nivel de pendejo.mp3',
  'tonto': './src/mp3/Su nivel de pendejo.mp3',
  'tonta': './src/mp3/Su nivel de pendejo.mp3',
  '😐': './src/mp3/Su nivel de pendejo.mp3',
  '🙄': './src/mp3/Su nivel de pendejo.mp3',
  '😜': './src/mp3/Su nivel de pendejo.mp3',
  '🤪': './src/mp3/Su nivel de pendejo.mp3',

  'tal vez': './src/mp3/Tal vez.mp3',
  'puede ser': './src/mp3/Tal vez.mp3',
  'posible': './src/mp3/Tal vez.mp3',
  '🧘‍♀️': './src/mp3/Tal vez.mp3',
  '🍦': './src/mp3/Tal vez.mp3',
  '🍡': './src/mp3/Tal vez.mp3',
  '🌮': './src/mp3/Tal vez.mp3',
  '🍕': './src/mp3/Tal vez.mp3',
  '🍔': './src/mp3/Tal vez.mp3',
  '🌭': './src/mp3/Tal vez.mp3',
  '🍖': './src/mp3/Tal vez.mp3',
  '😋': './src/mp3/Tal vez.mp3',
  '🎩': './src/mp3/Tal vez.mp3',

  'Te gusta el Pepino': './src/mp3/Te gusta el Pepino.mp3',
  '🥒': './src/mp3/Te gusta el Pepino.mp3',
  '🍆': './src/mp3/Te gusta el Pepino.mp3',
  'nepe': './src/mp3/Te gusta el Pepino.mp3',

  'Todo bien': './src/mp3/Todo bien.mp3',
  '😇': './src/mp3/Todo bien.mp3',
  '😃': './src/mp3/Todo bien.mp3',
  '😁': './src/mp3/Todo bien.mp3',
  '😄': './src/mp3/Todo bien.mp3',
  '🏂': './src/mp3/Todo bien.mp3',
  '⛷️': './src/mp3/Todo bien.mp3',
  '🏋️‍♂️': './src/mp3/Todo bien.mp3',
  '🏋️‍♀️': './src/mp3/Todo bien.mp3',
  '🤹‍♀️': './src/mp3/Todo bien.mp3',
  '🤹‍♂️': './src/mp3/Todo bien.mp3',
  '👌': './src/mp3/Todo bien.mp3',
  '👋': './src/mp3/Todo bien.mp3',
  '👍': './src/mp3/Todo bien.mp3',

  'Traigan le una falda': './src/mp3/Traigan le una falda.mp3',
  'Traiganle una falda': './src/mp3/Traigan le una falda.mp3',
  'Nina': './src/mp3/Traigan le una falda.mp3',
  'niña': './src/mp3/Traigan le una falda.mp3',
  'niño': './src/mp3/Traigan le una falda.mp3',

  'Y este quien es': './src/mp3/Y este quien es.mp3',
  'Y este quien poronga es': './src/mp3/Y este quien es.mp3',
  'Y este quien porongas es': './src/mp3/Y este quien es.mp3',
  'vida': './src/mp3/Y este quien es.mp3',

  'Goku pervertido': './src/mp3/Ya antojaron.mp3',
  'pervertido': './src/mp3/Ya antojaron.mp3',
  'pervertida': './src/mp3/Ya antojaron.mp3',
  'goku': './src/mp3/Ya antojaron.mp3',
  'antojen': './src/mp3/Ya antojaron.mp3',
  'antogen': './src/mp3/Ya antojaron.mp3',
  '😈': './src/mp3/Ya antojaron.mp3',
  '👿': './src/mp3/Ya antojaron.mp3',
  '👉👌': './src/mp3/Ya antojaron.mp3',
  '👌👈': './src/mp3/Ya antojaron.mp3',

  'abduzcan': './src/mp3/abduzcan.mp3',
  'Abduzcan': './src/mp3/abduzcan.mp3',
  'adbuzcan': './src/mp3/abduzcan.mp3',
  'Adbuzcan': './src/mp3/abduzcan.mp3',

  'TENGO LOS CALZONES': './src/mp3/admin-calzones.mp3',
  'Tengo los calzones': './src/mp3/admin-calzones.mp3',
  'tengo los calzones': './src/mp3/admin-calzones.mp3',
  '🥶': './src/mp3/admin-calzones.mp3',
  '😳': './src/mp3/admin-calzones.mp3',
  '😱': './src/mp3/admin-calzones.mp3',
  '😨': './src/mp3/admin-calzones.mp3',
  '🙀': './src/mp3/admin-calzones.mp3',
  'calzones': './src/mp3/admin-calzones.mp3',

  'anadieleimporta': './src/mp3/dylan1.mp3',
  'a nadie le importa': './src/mp3/dylan1.mp3',
  'y que': './src/mp3/dylan1.mp3',
  'no importa': './src/mp3/dylan1.mp3',
  'literal': './src/mp3/dylan1.mp3',

  'miarda de bot': './src/mp3/insultar.mp3',
  'mierda de bot': './src/mp3/insultar.mp3',
  'mearda de bot': './src/mp3/insultar.mp3',
  'Miarda de Bot': './src/mp3/insultar.mp3',
  'Mierda de Bot': './src/mp3/insultar.mp3',
  'Mearda de Bot': './src/mp3/insultar.mp3',
  'bot puto': './src/mp3/insultar.mp3',
  'Bot puto': './src/mp3/insultar.mp3',
  'Bot CTM': './src/mp3/insultar.mp3',
  'Bot ctm': './src/mp3/insultar.mp3',
  'bot CTM': './src/mp3/insultar.mp3',
  'bot ctm': './src/mp3/insultar.mp3',
  'bot pendejo': './src/mp3/insultar.mp3',
  'Bot pendejo': './src/mp3/insultar.mp3',
  'bot de mierda': './src/mp3/insultar.mp3',

  'baneado': './src/mp3/baneado.mp3',
  'Baneado': './src/mp3/baneado.mp3',
  'baneada': './src/mp3/baneado.mp3',
  '🤫': './src/mp3/baneado.mp3',

  'Cada': './src/mp3/basado.mp3',
  'Basado': './src/mp3/basado.mp3',
  'Basada': './src/mp3/basado.mp3',
  'Basadisimo': './src/mp3/basado.mp3',
  'BASADO': './src/mp3/basado.mp3',
  'basado': './src/mp3/basado.mp3',
  'basada': './src/mp3/basado.mp3',
  'Que basado': './src/mp3/basado.mp3',
  'Que basada': './src/mp3/basado.mp3',
  'que basado': './src/mp3/basado.mp3',

  'Bien pensado woody': './src/mp3/bien-pensado-woody.mp3',
  'bien pensado woody': './src/mp3/bien-pensado-woody.mp3',
  'Bien pensado': './src/mp3/bien-pensado-woody.mp3',
  'Bienpensado': './src/mp3/bien-pensado-woody.mp3',
  'Bien pensado woody': './src/mp3/bien-pensado-woody.mp3',
  'Bien pensada woody': './src/mp3/bien-pensado-woody.mp3',

  'Enhorabuena': './src/mp3/enhorabuena.mp3',
  'Enhorabuena': './src/mp3/enhorabuena.mp3',
  'Enhorabuena 🥳': './src/mp3/enhorabuena.mp3',
  '🥳': './src/mp3/enhorabuena.mp3',
  '🎉': './src/mp3/enhorabuena.mp3',
  '🎊': './src/mp3/enhorabuena.mp3',
  'Felicidades': './src/mp3/enhorabuena.mp3',
  'felicitaciones': './src/mp3/enhorabuena.mp3',

  'No puede ser': './src/mp3/no-puede-ser.mp3',
  'No lo puedo creer': './src/mp3/no-puede-ser.mp3',
  'No mames': './src/mp3/no-puede-ser.mp3',
  'No mames wey': './src/mp3/no-puede-ser.mp3',
  'No puede ser wey': './src/mp3/no-puede-ser.mp3',
  'no puede ser': './src/mp3/no-puede-ser.mp3',
  'no lo puedo creer': './src/mp3/no-puede-ser.mp3',
  'no mames': './src/mp3/no-puede-ser.mp3',
  'no mames wey': './src/mp3/no-puede-ser.mp3',
  'no puede ser wey': './src/mp3/no-puede-ser.mp3',
  'homero chino': './src/mp3/Homero chino.mp3',
  'sexo': './src/mp3/maau1.mp3',
  'jesucristo': './src/mp3/jesucristo.mp3',
  'la voz de hombre': './src/mp3/la-voz-de-hombre.mp3',
  'la oracion': './src/mp3/ora.mp3',
  'cancion1': './src/mp3/cancion.mp3',
  'masivo': './src/mp3/masivo-cancion.mp3',
  'ho me vengo': './src/mp3/vengo.mp3',
  'me pica los cocos': './src/mp3/me-pican-los-cocos.mp3',
  'mmm': './src/mp3/mmm.mp3',
  'moshi moshi': './src/mp3/moshi moshi.mp3',
  'murió el grupo': './src/mp3/Murio.m4a',
  'nadie te pregunto': './src/mp3/nadie te pregunto.mp3',
  'feliz navidad': './src/mp3/navidad.m4a',
  'niconico': './src/mp3/niconico.mp3',
  'no chu': './src/mp3/no chu.mp3',
  'no me hables': './src/mp3/no me hables.mp3',
  'no me hagas usar esto': './src/mp3/no me hagas usar esto.mp3',
  'no digas eso papu': './src/mp3/no-digas-eso-papu.mp3',
  'noche de paz': './src/mp3/Noche.mp3',
  'nyapasu': './src/mp3/otaku.mp3',
  'ohayo': './src/mp3/ohayo.mp3',
  'omaiga': './src/mp3/omaiga.mp3',
  'oni-chan': './src/mp3/Onichan.mp3',
  'orale': './src/mp3/orale.mp3',
  'pasa pack': './src/mp3/Elmo.mp3',
  'contexto': '/src/mp3/contexto.mp3',
  'pero esto': './src/mp3/pero-esto-ya-es-otro-nivel.mp3',
  'pika': './src/mp3/pikachu.mp3',
  'pokemon': './src/mp3/pokemon.mp3',
  'quién es tu senpai botsito': './src/mp3/Tu.mp3',
  'rawr': './src/mp3/rawr.mp3',
  'hablame': './src/mp3/sempai.mp3',
  'cagaste': './src/mp3/suspenso.mp3',
  'yoshi': './src/mp3/yoshi-cancion.mp3',
  'verdad que te engañe': './src/mp3/verdad-que-te-engane.mp3',
  'vivan': './src/mp3/vivan.mp3',
  'yamete': './src/mp3/Yamete-kudasai.mp3',
  'usted esta detenido': './src/mp3/usted esta detenido.mp3',
  'una pregunta': './src/mp3/una-pregunta.mp3',
  'freefire': './src/mp3/freefire.mp3',
  'aguanta': './src/mp3/aguanta.mp3',
  'es viernes': './src/mp3/es viernes.mp3',
  'que quede vos': './src/mp3/chabona.mp3',
  'feriado': './src/mp3/feriado.mp3',
  'borracho': './src/mp3/borracho.mp3',
  'delivery': './src/mp3/delivery.mp3',
  'putos': './src/mp3/tarado.mp3',
  'bardo': './src/mp3/bardo.mp3',
  'saliste del grupo': './src/mp3/saliste del grupo.mp3',
  'no agregue': './src/mp3/no agregue.mp3',
  'internet gratis': './src/mp3/internet gratis.mp3',
  'donde esta': './src/mp3/es grupo.mp3',
  'q onda': './src/mp3/q onda.mp3',
  'la toxica': './src/mp3/la toxica.mp3',
  'bebesita': './src/mp3/bebesita.mp3',
  'tka': './src/mp3/tka.mp3',
  'takataka': './src/mp3/takataka.mp3',
  'no la pienso': './src/mp3/no la pienso.mp3',
  'loli conmigo venga': './src/mp3/loli conmigo.mp3',
  'bruno': './src/mp3/bruno.mp3',
  'soy guapo': './src/mp3/soy guapo.mp3',
  'dj bot': './src/mp3/dj bot.mp3',
  'quevedo quedate': './src/mp3/quedate.mp3',
  'chiste': './src/mp3/dylan2.mp3',
  'gaspi y la minita': './src/mp3/gaspi6.mp3',
  'gaspi y la mina': './src/mp3/gaspi6.mp3',
  'ig de la minita': './src/mp3/gaspi6.mp3',
  'gaspi frase': './src/mp3/gaspi9.mp3',
  'frases': './src/mp3/gaspi9.mp3',
  'se pudrió': './src/mp3/sonbare5.mp3',
  'se que re pudrió': './src/mp3/sonbare5.mp3',
  'goo': './src/mp3/sonbare14.mp3',
  'temazo': './src/mp3/sonbare14.mp3',
  'fua temon': './src/mp3/sonbare14.mp3',
  'vamos': './src/mp3/vamo.mp3',
  'vamo': './src/mp3/vamo.mp3',
  ':V': './src/mp3/viejo1.mp3',
  'v:': './src/mp3/viejo1.mp3',
  'V:': './src/mp3/viejo1.mp3',
  'no me hables': './src/mp3/no me hables.mp3',
  'sus': './src/mp3/sus.mp3',
  'el amor': './src/mp3/el amor.mp3',
  '😍': './src/mp3/el amor.mp3',
  'escupido': './src/mp3/escupido.mp3',
  'mi bebito fui': './src/mp3/fui.mp3',
  'fui fui': './src/mp3/fui.mp3',
  'no soy pati': './src/mp3/no soy pati.mp3',
  'oxxo': './src/mp3/oxxo.mp3',
  'oxxo mmm': './src/mp3/oxxo.mp3',
  'sexo': './src/mp3/maau1.mp3',
  'Sexo': './src/mp3/maau1.mp3',
  'Hora de sexo': './src/mp3/maau1.mp3',
  'hora de sexo': './src/mp3/maau1.mp3',
  'que linda noche': './src/mp3/que linda noche.mp3',
  'linda nocheee': './src/mp3/que linda noche.mp3',
  'sabosito': './src/mp3/sabosito.mp3',
  'te elimino': './src/mp3/te elimino.mp3',
  'te saber': './src/mp3/te saber.mp3',
  'te sabes': './src/mp3/te saber.mp3',
  'Temon': './src/mp3/temon.mp3',
  'temon': './src/mp3/temon.mp3',
  'trabajo': './src/mp3/trabajo.mp3',
  'mami yo que digo a ti': './src/mp3/mami yo que digo a ti.mp3',
  'Mujer': './src/mp3/mujer.mp3',
  'dama': './src/mp3/mujer.mp3',
  'mujeres': './src/mp3/mujer.mp3',
  'te felicito': './src/mp3/te felicito.mp3',
  'espera vegeta escucha': './src/mp3/te felicito.mp3',
  'vegeta': './src/mp3/te felicito.mp3',
  'siu': './src/mp3/siu.mp3',
  'siiuu': './src/mp3/siu.mp3',
  'ssiiuu': './src/mp3/siu.mp3',
  'siuuu': './src/mp3/siu.mp3',
  'siiuuu': './src/mp3/siu.mp3',
  'siiiuuuu': './src/mp3/siu.mp3',
  'siuuuu': './src/mp3/siu.mp3',
  'siiiiuuuuu': './src/mp3/siu.mp3',
  'SIIIIUUU': './src/mp3/siu.mp3',
  'ara ara': './src/mp3/Ara.mp3',
  'Hey': './src/mp3/jai.mp3',
  'Hei': './src/mp3/jai.mp3',
  'hey': './src/mp3/jai.mp3',
  'HEY': './src/mp3/jai.mp3',
  'Joder': './src/mp3/joder.mp3',
  'joder': './src/mp3/joder.mp3',
  ':c': './src/mp3/toma.mp3',
  'Amongos': './src/mp3/sus.mp3',
  'among us': './src/mp3/sus.mp3',
  'Among us': './src/mp3/sus.mp3',
  'Among': './src/mp3/sus.mp3',
  'te amo': './src/mp3/Te-amo.mp3',
  'teamo': './src/mp3/Te-amo.mp3',
  'Estoy triste': './src/mp3/violin.mp3',
  'ESTOY TRISTE': './src/mp3/violin.mp3',
  'estoy triste': './src/mp3/violin.mp3',
  'Triste': './src/mp3/violin.mp3',
  'TRISTE': './src/mp3/violin.mp3',
  'triste': './src/mp3/violin.mp3',
  'Troste': './src/mp3/violin.mp3',
  'TROSTE': './src/mp3/violin.mp3',
  'troste': './src/mp3/violin.mp3',
  'Truste': './src/mp3/violin.mp3',
  'TRUSTE': './src/mp3/violin.mp3',
  'truste': './src/mp3/violin.mp3',
  'un Pato': './src/mp3/pato.mp3',
  'un pato': './src/mp3/pato.mp3',
  'un pato que va caminando alegremente': './src/mp3/pato.mp3',
  'Un pato': './src/mp3/pato.mp3',
  'Un Pato': './src/mp3/pato.mp3',
  'UwU': './src/mp3/UwU.mp3',
  'uwu': './src/mp3/UwU.mp3',
  'Uwu': './src/mp3/UwU.mp3',
  'uwU': './src/mp3/UwU.mp3',
  'UWU': './src/mp3/UwU.mp3',
  'fiesta viernes': './src/mp3/viernes.mp3',
  'viernes': './src/mp3/viernes.mp3',
  'Viernes': './src/mp3/viernes.mp3',
  'viernes fiesta': './src/mp3/viernes.mp3',
  'WTF': './src/mp3/wtf.mp3',
  'wtf': './src/mp3/wtf.mp3',
  'Wtf': './src/mp3/wtf.mp3',
  'wataf': './src/mp3/wtf.mp3',
  'watafac': './src/mp3/wtf.mp3',
  'watafack': './src/mp3/wtf.mp3',
  'Yokese': './src/mp3/yokese.mp3',
  'yokese': './src/mp3/yokese.mp3',
  'YOKESE': './src/mp3/yokese.mp3',
  'vetealavrg': './src/mp3/vete a la verga.mp3',
  'vete a la vrg': './src/mp3/vete a la verga.mp3',
  'vete a la verga': './src/mp3/vete a la verga.mp3',
  'no funciona': './src/mp3/0851d591-d9fe-4879-8f38-a2f68d5ade60.webp',
  'good': './src/mp3/2a332ffc-a34f-4a5c-87d9-6e04a9e8e0d4.webp',
  'bien': './src/mp3/2a332ffc-a34f-4a5c-87d9-6e04a9e8e0d4.webp',
  'jaja': './src/mp3/75cf9f9c-01bc-497c-8557-6ac966c913c8.webp',
  'gracioso': './src/mp3/75cf9f9c-01bc-497c-8557-6ac966c913c8.webp',
  'maricon': './src/mp3/6c4c3326-7e85-43b6-bcae-31c968e466d9.webp',
  'negro de mierda': './src/mp3/15775cfe-0c4d-4fed-8ba3-ade6131c0883.webp',
  'hola': './src/mp3/67b4245f-4de9-46dd-8d09-35e829aa0c9f.webp',
  'claro': './src/mp3/da786cb2-5d14-4a46-a997-94aaf3011ae5.webp',
  'meme': './src/mp3/d93d2ae4-3a0c-4c5d-ae77-759d924d4362.webp',
  'epic': './src/mp3/2e038fd2-b71a-44f1-9774-d2b6450d6973.webp',
  'lol': './src/mp3/2e038fd2-b71a-44f1-9774-d2b6450d6973.webp',
  'delux': './src/mp3/d83d64d1-e2cb-4591-9a89-d5a7fc66fef3.webp',
  'bad': './src/mp3/d83d64d1-e2cb-4591-9a89-d5a7fc66fef3.webp',
  'bueno': './src/mp3/4a4a0e66-2c47-45b7-8ae8-5a5e0756fbd1.webp',
  'good': './src/mp3/4a4a0e66-2c47-45b7-8ae8-5a5e0756fbd1.webp',
  'si': './src/mp3/8d92c8e3-9057-470f-a6b3-c6faeec644c7.webp',
  'no': './src/mp3/cadf90ac-3828-46af-b0e0-890d56013fd0.webp',
  'correcto': './src/mp3/8f0d5a68-258e-4ae5-bae4-42e1f9a44be6.webp',
  'correct': './src/mp3/8f0d5a68-258e-4ae5-bae4-42e1f9a44be6.webp',
  'siii': './src/mp3/8d92c8e3-9057-470f-a6b3-c6faeec644c7.webp',
  'si sí': './src/mp3/8d92c8e3-9057-470f-a6b3-c6faeec644c7.webp',
  'nooo': './src/mp3/cadf90ac-3828-46af-b0e0-890d56013fd0.webp',
  'not': './src/mp3/cadf90ac-3828-46af-b0e0-890d56013fd0.webp',
  'porque': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'perdón': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'sory': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'sorry': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'sory': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'lo siento': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'mis disculpas': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'lo siento mucho': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'disculpa': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'disculpame': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'la pasé mal': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'siento': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'llorar': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'estoy llorando': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'llorando': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'ok': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'ok': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'está bien': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'okey': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'okey': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'de acuerdo': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'okay': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'okey': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'Está bien': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'Acepto': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'Acepto': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'acepto': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'acepto': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'la cagué': './src/mp3/la cague.mp3',
  'la cagaste': './src/mp3/la cague.mp3',
  'la cagaste': './src/mp3/la cague.mp3',
  'la cagaste': './src/mp3/la cague.mp3',
  'la cague': './src/mp3/la cague.mp3',
  'la cague': './src/mp3/la cague.mp3',
  'la cague': './src/mp3/la cague.mp3',
  'la cague': './src/mp3/la cague.mp3',
  'la cague': './src/mp3/la cague.mp3',
  'la cague': './src/mp3/la cague.mp3',
  'la cague': './src/mp3/la cague.mp3',
  'la cagaste': './src/mp3/la cague.mp3',
  'la cague': './src/mp3/la cague.mp3',
  'la cague': './src/mp3/la cague.mp3',
  'la cague': './src/mp3/la cague.mp3',
  'cagada': './src/mp3/la cague.mp3',
  'la cague': './src/mp3/la cague.mp3',
  'cagué': './src/mp3/la cague.mp3',
  'cagada': './src/mp3/la cague.mp3',
  'no fue': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'cagada': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'pito': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no quiero': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no quiero': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no quiero': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'me estas': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no se': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no se': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no se': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no entiendo': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no entiendo': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no entiendo': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no entiendo': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'creo que si': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'creo': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no se': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no entiendo': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'me estas': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no entiendo': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no entiendo': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'creo': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no sé': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no entiendo': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'sii': './src/mp3/8d92c8e3-9057-470f-a6b3-c6faeec644c7.webp',
  'ok': './src/mp3/4f9d77d6-b858-466e-b872-1672a03a628e.webp',
  'no': './src/mp3/cadf90ac-3828-46af-b0e0-890d56013fd0.webp',
  'nooo': './src/mp3/cadf90ac-3828-46af-b0e0-890d56013fd0.webp',
  'No': './src/mp3/cadf90ac-3828-46af-b0e0-890d56013fd0.webp',
  'si': './src/mp3/8d92c8e3-9057-470f-a6b3-c6faeec644c7.webp',
  'yes': './src/mp3/8d92c8e3-9057-470f-a6b3-c6faeec644c7.webp',
  'good': './src/mp3/4a4a0e66-2c47-45b7-8ae8-5a5e0756fbd1.webp',
  'very good': './src/mp3/4a4a0e66-2c47-45b7-8ae8-5a5e0756fbd1.webp',
  'bad': './src/mp3/d83d64d1-e2cb-4591-9a89-d5a7fc66fef3.webp',
  'very bad': './src/mp3/d83d64d1-e2cb-4591-9a89-d5a7fc66fef3.webp',
  'pato': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no': './src/mp3/cadf90ac-3828-46af-b0e0-890d56013fd0.webp',
  'no': './src/mp3/cadf90ac-3828-46af-b0e0-890d56013fd0.webp',
  'no': './src/mp3/cadf90ac-3828-46af-b0e0-890d56013fd0.webp',
  'si': './src/mp3/8d92c8e3-9057-470f-a6b3-c6faeec644c7.webp',
  'sí': './src/mp3/8d92c8e3-9057-470f-a6b3-c6faeec644c7.webp',
  'ya no': './src/mp3/8d92c8e3-9057-470f-a6b3-c6faeec644c7.webp',
  'ya no': './src/mp3/8d92c8e3-9057-470f-a6b3-c6faeec644c7.webp',
  'sí': './src/mp3/8d92c8e3-9057-470f-a6b3-c6faeec644c7.webp',
  'la cagué': './src/mp3/la cague.mp3',
  'no sé': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'lo siento': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'perdón': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'lo siento': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'lo siento': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'lo siento': './src/mp3/6ef9b145-5ab2-473d-bb6d-56f18a66e6a2.webp',
  'te lo juro': './src/mp3/te lo juro.mp3',
  'te lo prometo': './src/mp3/te lo juro.mp3',
  'fijate': './src/mp3/te lo juro.mp3',
  'mami': './src/mp3/te lo juro.mp3',
  'de mentira': './src/mp3/de mentira.mp3',
  'mentira': './src/mp3/de mentira.mp3',
  'fuera de mi casa': './src/mp3/fuera.mp3',
  'no quiero': './src/mp3/09d1d079-c7ea-4b43-9e14-741f4d6d2ff7.webp',
  'no me hables': './src/mp3/no me hables.mp3',
  'cancion del verano': './src/mp3/cancion.mp3',
  'musica del verano': './src/mp3/cancion.mp3',
  'temazo': './src/mp3/cancion.mp3',
  'top': './src/mp3/cancion.mp3',
  'tema': './src/mp3/cancion.mp3',
  'musica': './src/mp3/cancion.mp3',
  'musica': './src/mp3/cancion.mp3',
  'top': './src/mp3/cancion.mp3',
  'cancion': './src/mp3/cancion.mp3',
  'musica': './src/mp3/cancion.mp3',
  'top': './src/mp3/cancion.mp3',
  'el mejor': './src/mp3/el mejor.mp3',
  'temazo': './src/mp3/el mejor.mp3',
  'tema': './src/mp3/el mejor.mp3',
  'musica': './src/mp3/el mejor.mp3',
  'musica': './src/mp3/el mejor.mp3',
  'musica': './src/mp3/el mejor.mp3',
  'tema': './src/mp3/el mejor.mp3',
  'tema': './src/mp3/el mejor.mp3',
  'temazo': './src/mp3/el mejor.mp3',
  'tema': './src/mp3/el mejor.mp3',
  'el mejor': './src/mp3/el mejor.mp3',
  'musica': './src/mp3/el mejor.mp3',
  'musica': './src/mp3/el mejor.mp3',
  'musica': './src/mp3/el mejor.mp3',
  'musica': './src/mp3/el mejor.mp3',
  'musica': './src/mp3/el mejor.mp3',
  'musica': './src/mp3/el mejor.mp3',
  'el mejor': './src/mp3/el mejor.mp3',
  'la mejor': './src/mp3/la mejor.mp3',
  'mejor': './src/mp3/la mejor.mp3',
  'mejor': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'la mejor': './src/mp3/la mejor.mp3',
  'mejor': './src/mp3/la mejor.mp3',
  'la mejor': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'temazo': './src/mp3/la mejor.mp3',
  'temazo': './src/mp3/la mejor.mp3',
  'el mejor': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'la mejor': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'temazo': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3',
  'temazo': './src/mp3/la mejor.mp3',
  'tema': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'tema': './src/mp3/la mejor.mp3',
  'temazo': './src/mp3/la mejor.mp3',
  'tema': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'cancion del verano': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3',
  'temazo': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'cancion': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'musica': './src/mp3/la mejor.mp3',
  'musica del verano': './src/mp3/la mejor.mp3'

};
